services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx/mysite.conf:/etc/nginx/conf.d/mysite.conf:ro
    restart: unless-stopped
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3011:3011"
    restart: unless-stopped
  db:
      image: postgres:latest
      
      # This names your container so it's easy to find in 'docker ps'
      container_name: my_postgres
      
      # These variables define your login credentials
      environment:
        POSTGRES_USER: taha 
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydatabase
      
      # Maps port 5432 on your Mac to port 5432 inside the container
      ports:
        - "5432:5432"
      
      # This keeps your data safe on your Mac even if the container is deleted
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
        
      # Ensures the database restarts if your Mac reboots or Colima restarts
      restart: always
